[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs", "libpng", "libjpeg", "freetype"]

[phases.install]
cmds = ["composer install --no-interaction --optimize-autoloader"]

[phases.build]
cmds = [
    "php artisan key:generate --force",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "npm install && npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
